adapter: lora
base_model: /workspace/input_data/Qwen/Qwen2-0.5B-Instruct
bf16: auto
chat_template: llama3
dataset_prepared_path: null
datasets:
debug: null
deepspeed: null
device_map: auto
do_eval: true
early_stopping_patience: 2
save_steps: 150
eval_steps: 150
eval_batch_size: 4
eval_max_new_tokens: 128
# eval_steps: 200
eval_table_size: null
evals_per_epoch: null
flash_attention: true
fp16: false
fsdp: null
fsdp_config: null
gradient_accumulation_steps: 4
gradient_checkpointing: false
group_by_length: true
# hub_strategy: end
# hub_model_id: baby-dev/test
learning_rate: 0.0002
load_in_4bit: false
load_in_8bit: false
local_rank: null
logging_steps: 50
lora_alpha: 64
lora_dropout: 0.05
lora_fan_in_fan_out: null
lora_model_dir: null
lora_r: 32
lora_target_linear: true
lr_scheduler: constant
max_grad_norm: 1.0
max_steps: 1000
num_epochs: 5
micro_batch_size: 4
model_type: AutoModelForCausalLM
# optim_args:
#   adam_beta1: 0.9
#   adam_beta2: 0.95
#   adam_epsilon: 1e-5
optimizer: adamw_bnb_8bit
output_dir: miner_id_24
pad_to_sequence_len: true
resume_from_checkpoint: null
s2_attention: null
sample_packing: false
# save_steps: 200
saves_per_epoch: null
sequence_len: 512
strict: false
tf32: true
tokenizer_type: AutoTokenizer
train_on_inputs: false
trust_remote_code: true
val_set_size: 0.05
# wandb_entity: null
# wandb_mode: online
# wandb_name: 4d2bab76-4597-405a-80aa-8803157f8fdf
# wandb_project: Gradients-On-Demand
# wandb_run: your_name
# wandb_runid: 4d2bab76-4597-405a-80aa-8803157f8fdf
warmup_steps: 50
weight_decay: 0.0
xformers_attention: null
trust_remote_code: False
